---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure Jenkins init settings.
- include: settings.yml

- name: Start jenkins
  service: name=jenkins enabled=yes state=started

- name: Wait for Jenkins to start up before proceeding.
  shell: "curl -D - --silent --max-time 10 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  check_mode: no

- name: Create the docker group
  group:
    name: docker
    state: present

- name: Add jenkins' user to the docker group
  become: yes
  user:
    name: jenkins
    groups: docker
    append: yes
    state: present

- name: Restart docker service
  become: yes
  service:
    name: docker
    state: restarted

- name: Open jenkins' port
  firewalld:
    port: "{{ jenkins_http_port }}/tcp"
    state: enabled
  
- name: Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

# Update Jenkins and install configured plugins.
- include: plugins.yml