---

- hosts: prod
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'update'
      raw: apt-get update
      when: ansible_os_family == 'Debian'
    - name: 'install python2'
      raw: apt-get -y install python
      when: ansible_os_family == 'Debian'

  roles:
    - firewalld
    - user
    - docker
    