---
- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
    dest: "/usr/bin/docker-compose"
    mode: 0755


#- name: Install docker-compose
#  raw: curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > ./docker-compose 
#    && sudo mv ./docker-compose /usr/bin/docker-compose 
#    && sudo chmod +x /usr/bin/docker-compose


# docker_compose_path = /usr/bin/docker-compose
# docker_compose_version = 1.22.0